apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "vault-unsealer.name" . }}
    chart: {{ include "vault-unsealer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "vault-unsealer.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "vault-unsealer.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "vault-unsealer.fullname" . }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KUBERNETES_APISERVER
          value: {{ .Values.apiServer | quote }}