apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "vault-unsealer.name" . }}
    chart: {{ include "vault-unsealer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vault-unsealer.fullname" . }}:endpoints-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - "endpoints"
  verbs:
  - "get"
  - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-unsealer.fullname" . }}:endpoints-reader
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-unsealer.fullname" . }}:endpoints-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ .Release.Namespace }}